name: Generate Stats

on:
  schedule:
    - cron: "0 1,13 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Generate the stats widget in './dist/'
        run: node generate-stats.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_LOGIN: ${{ github.repository_owner }}
          OUT_DIR: dist

      - name: Show build status
        run: git status

      - name: Push new files to the stats-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: stats-output
          build_dir: dist
          commit_message: Update stats widget
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
